import streamlit as st
import plotly.graph_objects as go
import json
import os
# ---- FILE FOR SAVING STATE ----
STATE_FILE = "progress_state.json"

# ---- PAGE CONFIG ----
st.set_page_config(
    page_title="FIS Low-Carbon Strategy",
    page_icon="🌿",
    layout="centered"
)
# ---- HEADER ----
col1, col2, col3 = st.columns([1, 5, 1])
with col1:
    st.image("FIS_logo.png", width=80)
with col2:
    st.markdown(
        "<h1 style='text-align:center; color:#1B5E20;'>🌿 Low-Carbon Strategy </h1>",
        unsafe_allow_html=True
    )
    st.markdown(
        "<p style='text-align:center; color:#555;'>Track and visualize the sustainability implementation steps</p>",
        unsafe_allow_html=True
    )
with col3:
    st.image("FFS_logo.png", width=80)

st.markdown("<hr style='border:1px solid #ccc;'>", unsafe_allow_html=True)

# ======================================================
# 🌍 INTERACTIVE LOW-CARBON PLAN DIAGRAM
# ======================================================
st.subheader("🌍 FIS Low-Carbon Process Simulation")

st.markdown(
    """
<p style='font-size:16px; color:#444;'>
Click on each step below to see the details of the <b>Low-Carbon Strategy</b>.
</p>
""",
    unsafe_allow_html=True
)

# --- Step data ---
steps_info = {
    "Data Collection": {
        "color": "#2E7D32",
        "description": """
📊 **Data Collection Phase**  
Collect the data and information related to the organisation, product or service from different sources from within NSA/LOCs and stakeholders responsible for key deliverables, Data includes (energy consumption, transportation, materiel etc.)
"""
    },
    "FIS Integration": {
        "color": "#43A047",
        "description": """
🔗 **Integration with FIS Tool**  
Using the Tool FIS that is a CO2 Calculator, widely used international accounting standard to measure and report greenhouse gas emissions.
"""
    },
    "Excel Analysis": {
        "color": "#66BB6A",
        "description": """
📈 **Excel Analysis**  
Analyze the results generated by the FIS tool to identify the hotspots and determine which components contribute the most to the overall carbon footprint.
"""
    },
    "Corrective Actions": {
        "color": "#A5D6A7",
        "description": """
⚙️ **Corrective Actions**  
Thereby enabling the implementation of corrective measures and actions aimed at achieving low-carbon performance.
"""
    }
}
# --- Interactive step selector ---
selected_step = st.radio(
    "Select a step 👇",
    list(steps_info.keys()),
    horizontal=True
)

# --- Bubble diagram ---
fig = go.Figure()

for i, (step, data) in enumerate(steps_info.items()):
    fig.add_trace(go.Scatter(
        x=[i],
        y=[0],
        mode="markers+text",
        text=[step],
        textposition="middle center",
        textfont=dict(size=14, color="white"),
        marker=dict(
            size=120 if step == selected_step else 100,
            color=data["color"],
            line=dict(width=4 if step == selected_step else 2, color="#1B5E20"),
            opacity=1 if step == selected_step else 0.7
        ),
        hoverinfo="text"
    ))
    # flèches entre bulles
    if i < len(steps_info) - 1:
        fig.add_annotation(
            x=i + 0.5, y=0,
            ax=i + 0.1, ay=0,
            showarrow=True,
            arrowhead=3,
            arrowsize=1.5,
            arrowwidth=2,
            arrowcolor="#2E7D32"
        )
fig.update_layout(
    showlegend=False,
    xaxis=dict(visible=False),
    yaxis=dict(visible=False),
    height=350,
    plot_bgcolor="rgba(245,255,245,1)",
    paper_bgcolor="rgba(245,255,245,1)",
    margin=dict(l=40, r=40, t=40, b=40),
)

st.plotly_chart(fig, use_container_width=True)

# --- Display step description dynamically ---
st.markdown(
    f"""
<div style='background-color:{steps_info[selected_step]["color"]};
            color:white; padding:20px; border-radius:15px; margin-top:15px;'>
    {steps_info[selected_step]["description"]}
</div>
""",
    unsafe_allow_html=True
)

st.markdown("<hr style='border:1px solid #ccc;'>", unsafe_allow_html=True)

# ======================================================
# 📈 PROGRESS TRACKER (persistant)
# ======================================================
st.header("📈 Progress Tracker")

st.markdown(
    """
<p style='font-size:16px; color:#444;'>
Adjust the completion percentage for each step in your <b>Low-Carbon Strategy</b>.  
The total progress updates automatically.
</p>
""",
    unsafe_allow_html=True
)

# --- Load saved state ---
if os.path.exists(STATE_FILE):
    with open(STATE_FILE, "r") as f:
        saved_state = json.load(f)
else:
    saved_state = {}

tracker_steps = ["Data Collection", "FIS Integration/Other", "Excel Analysis", "Corrective Actions"]
progress_values = {}

for step in tracker_steps:
    key = step.replace(" ", "_").lower()
    default_value = saved_state.get(key, 0)
    progress_values[step] = st.slider(step, 0, 100, value=default_value, key=key)

# --- Save state automatically ---
save = {step.replace(" ", "_").lower(): progress_values[step] for step in tracker_steps}
with open(STATE_FILE, "w") as f:
    json.dump(save, f)

total_progress = int(sum(progress_values.values()) / len(tracker_steps))

st.markdown("---")
st.subheader("🌍 Overall Process Completion")
st.progress(total_progress)
st.write(f"**Overall Progress:** {total_progress}%")

if total_progress == 100:
    st.success("🎉 Excellent! Your low-carbon strategy is fully implemented.")
elif total_progress >= 70:
    st.info("🚀 You’re on the right path — keep improving sustainability actions.")
elif total_progress >= 30:
    st.warning("⚙️ Initial steps complete — continue refining your strategy.")
else:
    st.error("🛠️ Strategy still at an early stage. Let’s take action soon!")

st.markdown("<hr style='border:1px solid #ccc;'>", unsafe_allow_html=True)
st.markdown(
    """
<div style='text-align:center; color:#555; font-size:14px;'>
    La Fédération Française de Ski 
             Annecy
</div>
<div style='text-align:right; color:#555; font-size:14px;'>
    Roman RIBOUD -- Salma ATTAIBE
</div>
""",
    unsafe_allow_html=True
)

